config/routes.rb
Rails.application.routes.draw do

  resources :contacts do
    get "delete"
  end

  root to: "contacts#index"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true, numericality: true
  validates :email_address, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contacts = Contact.all
    @contact = Contact.create(contact_params)
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contacts = Contact.all
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
  end

  def delete
    @contact = Contact.find(params[:contact_id])
  end

  def destroy
    @contacts = Contact.all
    @contact = Contact.find(params[:id])
    @contact.destroy
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :address, :city, :state, :zip_code, :email_address, :phone_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Contact</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @contact.first_name %> <%= @contact.last_name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Contact", contact_path(@contact), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/contacts/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3><%= "Editing #{@contact.first_name} #{@contact.last_name}" %></h3>
    </div>
    <%= render "form" %>
  </div> <!-- content div -->
</div> <!-- dialog div -->

app/views/contacts/_form.html.erb
<%= form_for @contact, remote: true, html: { style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="form-group">
      <%= f.label :first_name, class:"control-label" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: "control-label" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :address, class:"control-label" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :city, class: "control-label" %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :state, class:"control-label" %>
      <%= f.text_field :state, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :zip_code, class: "control-label" %>
      <%= f.text_field :zip_code, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email_address, class: "control-label" %>
      <%= f.text_field :email_address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number, class: "control-label" %>
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/contacts/_index.html.erb
<div class="panel-group" id="contact-accordion">
  <% @contacts.each_with_index do |contact, index| %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">
          <a data-toggle="collapse" data-parent="#contact-accordion" href="#collapse<%= index.to_s %>"><%= contact.first_name %> <%= contact.last_name %></a>
        </h2>
      </div>
      <div id="collapse<%= index.to_s %>" class="accordion-body collapse">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <p><%= contact.address %></p>
              <p><%= contact.city %>, <%= contact.state %> <%= contact.zip_code %></p>
            </div>
            <div class="col-md-6">
              <p><%= contact.email_address %></p>
              <p><%= contact.phone_number %></p>
            </div>
          </div>
          <%= link_to "Edit Contact", edit_contact_path(contact), remote: true, class: "btn btn-default" %>
          <%= link_to "Delete", contact_delete_path(contact), remote: true, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>New Contact</h3>
    </div>
    <%= render "form" %>
  </div> <!-- content div -->
</div> <!-- dialog div -->

app/views/contacts/_save.html.erb
$("ul.errors").html("")
<% if @contact.errors.any? %>
  <% @contact.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".contact-index").html("<%= escape_javascript(render 'index') %>")
  $("#contact-modal").modal("hide")
<% end %>

app/views/contacts/create.js.erb
<%= render "save" %>

app/views/contacts/delete.js.erb
$("#contact-modal").html("<%= escape_javascript(render 'delete') %>")
$("#contact-modal").modal("show")

app/views/contacts/destroy.js.erb
<%= render "save" %>

app/views/contacts/edit.js.erb
$("#contact-modal").html("<%= escape_javascript(render 'edit') %>")
$("#contact-modal").modal("show")

app/views/contacts/index.html.erb
<div class="page-header">
  <h1 id="title-header">Address Book</h1>
  <button class="btn btn-default btn-lg" id="newbutton"><%= link_to "New Contact", new_contact_path, remote: true %></button>
</div>
<div class="container">

  <div class="contact-index">
    <%= render "index" %>
  </div>

  <div class="new-contact"></div>
  <div id="contact-modal" class="modal fade"></div>


</div>

app/views/contacts/new.js.erb
$("#contact-modal").html("<%= escape_javascript(render 'new') %>")
$("#contact-modal").modal("show")

app/views/contacts/show.html.erb
<h2><%= @contact.first_name %> <%= @contact.last_name %></h2>
<p><%= @contact.address %> <%= @contact.city %>, <%= @contact.state %> <%= @contact.zip_code %></p>
<button class="btn btn-default"><%= link_to "Edit Contact", edit_contact_path(@contact), remote: true %></button>
<button class="btn btn-danger"><%= link_to "Delete", contact_delete_path(@contact), remote: true %></button>

<div id="contact-modal" class="modal fade"></div>

app/views/contacts/update.js.erb
<%= render "save" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>

  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body "data-no-turbolink"> <!-- disabled turbolinks -->
  <!-- commented out navbar until search functionality is added -->
  <!-- <nav class="navbar navbar-default">
    <div class="container-fluid"> -->
      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
      </div> -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </ul> -->
      <!-- </div><!-- /.navbar-collapse -->
    <!-- </div><!-- /.container-fluid -->
  <!-- </nav> -->

<%= yield %>

</body>
</html>